excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift # Exclude files with a wildcard
line_length:
  warning: 350
  error: 500
cyclomatic_complexity:
  warning: 15
  error: 20
disabled_rules: # rule identifiers turned on by default to exclude from running
  - inclusive_language
  - type_body_length
  - file_length
